name: UseBlessingSkin
version: ${project.version}
main: com.github.hank9999.useblessingskin.bukkit.UseBlessingSkin
softdepend: [ "SkinsRestorer" ]
authors: ["hank9999"]
description: 让SkinsRestorer使用Blessing Skin Server搭建的皮肤站上的皮肤!
api-version: 1.13

permissions:
  UseBlessingSkin.admin:
    description: UseBlessingSkin Admin Perm
    default: op

commands:
  bskin:
    description: UseBlessingSkin Main Command